swagger: "2.0"
info:
  version: 0.1.0
  title: Employees
host: localhost
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      tags:
        - employees
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: bool
          format: int32
      responses:
        "200":
          description: An array of employees
          schema:
            $ref: '#/definitions/Employees'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /employees/{id}:
    get:
      summary: Info for a specific employee
      operationId: showEmployeeById
      tags:
        - employees
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the employee to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Employees'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Employee:
    type: "object"
    required:
      - id
      - name
      - surname
      - role
      - salary
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      surname:
        type: string
      salary:
        type: integer
  Employees:
    type: array
    items:
      $ref: '#/definitions/Employee'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
